# Generated by Django 5.1 on 2024-08-09 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='Special_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='drop_off',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='contactform',
            name='flight_nr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='pick_up',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
