# Generated by Django 5.1 on 2024-08-11 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_contactform_special_note_contactform_drop_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactform',
            name='ride_type',
            field=models.CharField(choices=[('comfort', 'Comfort'), ('van comfort', 'Van_Comfort'), ('black limo', 'Black_Limo')], default='comfort', max_length=20),
        ),
    ]
