# Generated by Django 5.1 on 2024-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_contactform_order_time_contactform_ride_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='ride_type',
            field=models.CharField(choices=[('comfort', 'Comfort'), ('van_comfort', 'Van Comfort'), ('black_limo', 'Black Limo')], default='comfort', max_length=20),
        ),
    ]
