# Generated by Django 5.1 on 2024-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_contactform_pick_up_time_alter_contactform_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='ride_type',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, max_length=20),
        ),
    ]
